### ISSUE TITLE
To Dos

### ISSUE THREAD

**Issue by amritbhanu** [ai-se/Pits_lda#15]
- [x] Talk to wei
- [x] do the lit (50-100) 
- [x] standard practice about toolkits, parameters and validation
- [x] what anyone else concluded in SE domain?
- [ ] Can you get the data in order to replicate? From a senior recent study with high citations.
- [x]  ICSE, FSE, RE, MSR, TSE, TOSEM, ESEM, JSS (Journal of Systems and Software), ISTR, IST
- [x] Can you find stability in their results? Can you fix them using DE?

----------------------------------------

## Papers
- Online LDA [[23]] (http://papers.nips.cc/paper/3902-online-learning-for-latent-dirichlet-allocation.pdf)
- [[41]] (http://machinelearning.wustl.edu/mlpapers/paper_files/jmlr10_newman09a.pdf) presents an algorithm for distributed Gibbs sampling
- [[67]] (http://delivery.acm.org/10.1145/2190000/2187955/p879-zhai.pdf?ip=152.7.224.6&id=2187955&acc=ACTIVE%20SERVICE&key=6ABC8B4C00F6EE47%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=767874599&CFTOKEN=67256149&__acm__=1460645192_0ebeb9a8a675995b36cd40a222a9f268) proposes a MapReduce parallelization framework that uses variational inference as the underlying algorithm
- [[19]] (http://www.pnas.org/content/101/suppl_1/5228.full.pdf) presents the Gibbs sampling method for LDA inference
- Labeled LDA: [[48]] (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.332.184&rep=rep1&type=pdf) presents a generative model for modeling document collections where the documents are associated with labels
- Dirichlet Forest LDA [[3]] (http://delivery.acm.org/10.1145/1560000/1553378/p25-andrzejewski.pdf?ip=152.7.224.6&id=1553378&acc=ACTIVE%20SERVICE&key=6ABC8B4C00F6EE47%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35%2E4D4702B0C3E38B35&CFID=767874599&CFTOKEN=67256149&__acm__=1460645331_96a0b29e22ef6a5e3fcfea2190515565)
- Logic LDA: [[4]] (https://e-reports-ext.llnl.gov/pdf/463169.pdf)
- Quad-LDA: [[42]] (http://papers.nips.cc/paper/4291-improving-topic-coherence-with-regularized-topic-models.pdf) In order to improve the coherence of the keywords per topic learned by LDA.
- NMF-LDA: Similar to Quad-LDA, [[64]] (http://www.anthology.aclweb.org/N/N15/N15-1074.pdf)
- Markov Random Topic Fields (MRTF): [[27]] (http://www.aclweb.org/old_anthology/P/P09/P09-2.pdf#page=311)
- Interactive Topic Modeling (ITM): [[26]] (http://download.springer.com/static/pdf/832/art%253A10.1007%252Fs10994-013-5413-0.pdf?originUrl=http%3A%2F%2Flink.springer.com%2Farticle%2F10.1007%2Fs10994-013-5413-0&token2=exp=1460646442~acl=%2Fstatic%2Fpdf%2F832%2Fart%25253A10.1007%25252Fs10994-013-5413-0.pdf%3ForiginUrl%3Dhttp%253A%252F%252Flink.springer.com%252Farticle%252F10.1007%252Fs10994-013-5413-0*~hmac=378bce93b852523b3f9fcbbfb00f87ffe9a376bfc5a530341badc67b9127dd54) proposes the first interactive framework for allowing users to iteratively refine the topics discovered by LDA by adding constraints that enforce that sets of words must appear together in the same topic
- [[47]] (http://www.cs.cmu.edu/~wcohen/10-605/papers/fastlda.pdf) proposes Fast-LDA by constructing an adaptive upper bound on the sampling distribution and achieves a faster inference

**Comment by timm** [comment]
you've actually finished 5 of the 7 items written above? so isthere a paper written? notes somewhere taken?

**Comment by amritbhanu** [comment]
here is the notes, https://github.com/ai-se/Pits_lda/blob/master/Papers/papers_SE.md


- [ ] Next to dos are other than SE domain, and find some more papers which talks about it.
